### PR TITLE
MNT: rerender

### LINKED ISSUE #64: @conda-forge-admin, please rerender
### Additional comment:

_No response_

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #64.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

Fixes #64

### CODE REVIEW

**Comment by h-vetinari** [comment]
I think this is necessary to unblock https://github.com/conda-forge/nordugrid-arc-feedstock/pull/43 (see comment there), not least due to libxml2 2.9 vs. 2.10

**Comment by chrisburr** [comment]
Thanks @h-vetinari! 🍰

**Comment by h-vetinari** [comment]
Ah damn, the bot isn't smart enough to bump the build number... 🤦

**Comment by chrisburr** [comment]
😆 Done: https://github.com/conda-forge/xrootd-feedstock/commit/10d9da818a12453b5780930001db979732fcc430

**Pull request merged**
